### ISSUE TITLE
Improve design of Timesheet/Entries page

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#2]
Maybe include timesheet stats and remove table layout

**Comment by JHSheridan** [comment]
I think one thing that is confusing currently is the timesheets > tasks > entries hierarchy. As I understand it, a timesheet is a client/customer, a task is something you can perform for a client/customer, and an entry is a time period filed under a task.

I think there is a better way to classify and organize these terms that will make things much more intuitive for the user.

**Clients**: Clients are made up of contact information about the client. 

**Projects**: a project is a group of tasks you can perform for a client. Tasks are basically just different hourly rates you can charge for different types of work.

**Timesheet**: a timesheet is a list of entries. Entries have an associated client, project, task, start time, and end time.

I think the Timesheet page ends up being the most important and most used page for users. Most of what is done in an app like this is logging time and editing those logs. I incorporated those actions into the following wireframes for the Timesheet page.

![day view](https://cloud.githubusercontent.com/assets/725786/25454394/eaab3a76-2a91-11e7-8d94-e327bb84088b.jpg)

![week view](https://cloud.githubusercontent.com/assets/725786/25454397/ef25bb1c-2a91-11e7-9d60-0f54848cff03.jpg)

The day view is the default layout when you hit the Timesheet page. You can use the big input box at the top to quickly start tracking time. As those timers are stopped and logged, they appear below in sequential order. This way, you get an overview of your entire day, and even down to yesterday as your scroll.

The week view is also accessible via the timesheet page. Week view breaks down your Timesheet a little bit differently. Instead of a list, you get a table with days of the week up top, and projects listed on the side. This is a much more useful view when trying to get an overview of what you've done for a week, and you should also be able to edit these.

Thoughts?

**Comment by cdubz** [comment]
100% agree with this. I am still a bit confused by the hierarchy, actually and I think your proposed structure would be much more clear.

Also love those wireframes - perhaps an opportunity to use Bootstrap v4 flexbox layout instead of tables, for better mobile support?

**Comment by overshard** [comment]
I like the idea of the Client > Project > Entries naming instead of Timesheet > Task, I'm definitely going to think about that for a while as that does seem to be closer to what I envisioned. I also like inlining the timer and having the ability to restart a timer for a task. I also love that you split the days up in the listing, that's very clean and something I do is go back and review the current day's entries, I definitely want to incorporate that.

I dislike the daily/weekly views on the timesheet/entries, I believe this should be left to reporting and the timesheet/entries page should be purely for entering new time and a quick review of recently entered.

**Comment by overshard** [comment]
@cdubz I think we definitely have to move off of tables, they just destroy mobile support...

**Comment by JHSheridan** [comment]
@cdubz you are correct about tables for sure. I definitely wouldn't implement these as tables, I was just speaking in a general sense regarding how they are laid out. I should have used less confusing language.

@overshard I'm glad you like the idea. I'm happy to iterate some more over it, and I can definitely help with the front-end implementation of these.

I take your point about keeping things simple for quick review. My reason for the week view is a specific use case that I think almost everyone who enters time sheets deals with. At the end of the week, you want to see where your time went, and you also may need to edit some things to make sure all of the hours add up. I can see this working in reports as well, but may be harder to implement the editing. Open to all ideas, just wanted to post my rationale.

**Comment by overshard** [comment]
@JHSheridan I've never reviewed a current week but I review myself daily maybe that would be a better workflow for myself. I won't totally dismiss the idea if that's something many people want and having it in the entries view would make it easier to implement the editing. I see your point. We'll keep that on the table!

**Comment by JHSheridan** [comment]
Sounds like a plan. 

For now, I'll focus on refining the daily view since we'll definitely need something like that. I'll probably do another round or two in Figma, then I can help out with actually implementing something like this in the templates.

**Comment by overshard** [comment]
@JHSheridan I would like to see some design iterations over Project + Client relationships too. I feel like a Project page is not required and we should have a combined Project + Client page that allows you to select a Client and view the projects with the ability to add new clients and projects on one page. I feel like a Project page is just a frustrating intermediary step and how we have it laid out now with just a giant list of tasks and timesheets they are attached two is just bad.

**Comment by JHSheridan** [comment]
That makes sense. Let me see what I can come up with.

**Comment by overshard** [comment]
I'm going to start reworking the models and API to reflect the Client + Project workflow as that makes infinitely more sense the more I contemplate it and we can hold off on major front-end revisions till @JHSheridan sees what he can come up with.

**Comment by overshard** [comment]
In e107ecd6c5b5513c2322e5d86637524dd5d4b5c5 I've refactored everything to use the Client > Project workflow instead of the confusing Timesheet > Task, have done nothing with the design yet but we've started!

**Comment by overshard** [comment]
I've went ahead and combined the Client and Project pages in f73aad4933c9c19fd9af04f2b8ee350ebffe6574 , I don't like the design on it right now but it's s start.

**Comment by overshard** [comment]
I am happy that I have now combined the client and project pages but I am very unhappy with the current design and how it's listed. I think it's very messy and hard to navigation. I'm open for any and all suggested improvements with examples if anyone wishes to provide any.

**Comment by JHSheridan** [comment]
I put in some more work on the Timesheet page. I moved from the wireframe above to something that is closer to an actual design.

![day-view](https://cloud.githubusercontent.com/assets/725786/25493361/80e72dca-2b3b-11e7-8dbe-7b90dca388ee.jpg)

Thoughts?

**Comment by JHSheridan** [comment]
I can definitely put some time into the Clients/Projects page as well.

I think it may be useful to create a separate issue for Client/Projects design work. I suppose we will continue to discuss and iterate on the Timesheets page, which should go here, and we'll need a parallel discussion for the Clients/Projects page. Just changing the title makes it a bit confusing.

**Comment by overshard** [comment]
This is really nice, definitely getting really close to exactly what we want. Only three things:

1. I'm not sure we want to bother with the "Task" element anymore. So it would be Client, Project selectors? Project being a subset of client depending on the client selection. Is the drill down into tasks important for a basic timesheet and invoicing? I want to say yes but I don't want to add additional complexity where we need not have it. Client > Project > Task or just Client > Project.
2. Editing entries is a must, I will sometimes fat finger a number and hit enter before I double check, how can we incorporate an edit button somewhere on here, I don't want it to be a hover show up button because hover effects don't work on touch screens and going all the way to the admin is lame for quick fixes.
3. (This maybe doesn't effect what you are giving us because it is a static image but I want to make a note of it) I want a way to manually enter time too so if someone starts to manually enter a duration the Start button should change to say Add seamlessly. Similarly once started it will say Stop and once stopped, since there is a time there, it will say Add.

I'm going to start in on implementing the timesheet exactly how you have it here later tonight!

**Comment by cdubz** [comment]
Some quick thoughts - 

1. I agree that Client -> Project should be enough. Entry notes fields could be used to provide "task level" sort of detail, if desired.
1. With the current interface proposal, what about just click/tap (or maybe double-click/tap) to expose edit fields for a record? I *think* this would be intuitive enough and would save UI space.

**Comment by JHSheridan** [comment]
1. I think whether tasks is necessary is debatable. It's main use in other time tracking and invoicing apps I've used is to assign different billable rates to different types of work. For instance, an agency may charge the same client one rate for project management, another for design, and another for programming. Maybe there's another mechanism other than tasks for that use case?

2. Good idea. I'll try to incorporate this into the next iteration.

3. This makes sense. I definitely see the start button being dynamic in the way you described.

I'll have some time this weekend to do a lot more on this. Now that we have the basic design idea together, I can start submitting some pull requests instead of just static images.

**Comment by overshard** [comment]
I like the click/tap to edit idea, and I assume just hit enter to save but is there some way we could allude to that for people who are less tech savvy to try?

Also I assume this is for just a personal time sheet, and the report system is used to see all users time? We won't show all users via this view?

**Comment by overshard** [comment]
Okay, we'll just exclude task for now. I understand tracking different billable rates and such and I would like to incorporate that but lets not add too many features or we'll be working on a 1.0 release for a year. I will add it to a list of feature suggestions for 2.0!

**Comment by JHSheridan** [comment]
Yes... We can try to use some sort of visual cue to for the click/tap to edit idea.

Yes... this is intended to just be the timesheet of the user who is logged in. At least for now, I think reports are a good place to look at other people's timesheets.

I agree with you on limiting scope for 1.0. Don't want to get too far ahead of ourselves.

**Comment by overshard** [comment]
I've gotten many of the basics from @JHSheridan 's design up in 78eb30d. Need to:

- Add functionality to the restart button
- Add functionality to the menu button so people can select delete, edit and maybe other options?
- Format dates, probably should be handled by the API for localization purposes
- Limit entries to current user only
- Add error handling for when no project is selected
- Add fix to when duration is completely removed manually Add button still says Add and does not update with manually entry to add
- Project dropdown needs to specify Client organizational structure, it's confusing right now
- Improve mobile layout, using bootstrap columns and not a table now though so shouldn't be too bad.

**Comment by overshard** [comment]
Few interesting things to note here after cdubz's update, still much better than what I had, progress was made!

- [ ]  For the first entry on a new day the entry will not appear until you refresh. Subsequent entries show up just fine. (Need to unshift a new date to the dates.)
- [ ] If you edit an entry then go back and use the normal entry submit form it will look like it removed your edit till you refresh the page.
- [ ] We need to remove the dropdown marker on the vertical ellipsis menu button for edit, restart, delete, as it is redundant.

**Comment by overshard** [comment]
Fixed a few things for this in b61a6f4

**Comment by overshard** [comment]
I'm pretty happy with the timesheet/entries page design at this point so we are moving on to other things and can revisit this in the future if needed after 1.0
