### ISSUE TITLE
Taking forever to connect

### ISSUE THREAD

**Issue by aniljava** [overshard/timestrap#23]
Page load gets hangs at the middle of loading, some part gets downloaded while other gets stalled for very long time. Same problem with Chrome and Firefox.

![1493053425](https://cloud.githubusercontent.com/assets/412569/25349188/26339756-28de-11e7-86ae-5f5789c409b3.jpg)

htop does not show any unusual usage.

**Comment by overshard** [comment]
These are just static files which don't actually touch the backend so I'm curious why they are hanging. What environment do you have this setup on? Ubuntu, Mac OS, Windows? Are you going through a reverse proxy?

**Comment by overshard** [comment]
Also have you set Debug = False? If you've set Debug to False and have not setup a system to serve static files that could also be the cause. If you wish to serve static files through Django itself look at our heroku config.

**Comment by aniljava** [comment]
Ubuntu. Accessing as http://127.0.0.1:8000/
My first thought was if the number of threads/connection is limited. No experience with django to go further.

Followed README.md for installation, no change on settings.

**Comment by overshard** [comment]
Someone else had this same problem and they stopped the process, started it again and reconnected and it worked then. I think this may all be caused by django-compressor so I'll have a look at it.

**Comment by overshard** [comment]
@aniljava I honestly can not recreate an instance where the files do a network timeout and I don't know where to start remote debugging this. Can you try deleting your virtualenv and starting from scratch using the new information in the readme? I hate to force you to try the classic "reboot it" but I don't know what else to attempt since you've already done that apparently but I don't know what else to do and we have had some improvements to documentation and code.

**Comment by overshard** [comment]
Closing this as there has been no response to it and it seems to be working for everyone else.
