### ISSUE TITLE
Heroku Build

### ISSUE THREAD

**Issue by marthesselink** [overshard/timestrap#35]
I wanted to try using this app with Heroku. Heroku and Python are new to me so I just started trying things.
I forked timestrap so that Heroku could acces the repo on my account to build it.

When building I get this error:

```
-----> Compressing static files
       CommandError: Compressor is disabled. Set the COMPRESS_ENABLED setting or use --force to override.
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

I tried a few thing to enable the compression and I guess it had something to do with Django, but I couldn't find a solution to build the project. Is there a guide to follow on how to build this app using Heroku or am I just doing something wrong?

Thanks in advance

**Comment by overshard** [comment]
I'm checking this out, my guess is that the post_compile command (https://github.com/overshard/timestrap/blob/master/bin/post_compile) needs to have --force set on compress command we run there or we need to set COMPRESS_ENABLED = True in heroku settings. I'm not sure why it's not defaulting to True though since we it should when DEBUG = False. I need to make sure that it's using the right settings file on push.

**Comment by overshard** [comment]
I just tested a few deployments and did not get this error, did you change the DJANGO_SETTINGS_MODULE value at all?

More specifically did you use the Heroku Deploy button or did you fork and git push directly to heroku without specifying the settings module?
