### ISSUE TITLE
Update totals on entries page when adding, restarting, or editing an entry

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#45]

**Comment by cdubz** [comment]
Any opinion about doing this in the front end? I *think* the only other option would be to somehow make the totals an independent tag so they could be updated without refreshing the entire list of entities. Seems like some simple jQuery would be an easy compromise here - it would just need to parse the strings and do the math.

**Comment by overshard** [comment]
It should be done on the frontend, once a edit, add, or delete is successful we should, in the success then() from the promise, update totals. + the diff of the edited, + the new added entirely, or - the deleted.

**Comment by overshard** [comment]
Also, this doesn't need to use jQuery, we can just, `this.totalTime = addTotal(totalTime, newTime)`, and same for subtotal. This is where `addTotal` combines two `HH:MM` strings. It could be named `combineTotal` and support a negative in front of the `newTime` and support subtraction too. Whatever works.

**Comment by cdubz** [comment]
I took a brief stab at this but didn't get far enough to PR anything. RiotJS seems to be a bit of issue here - by attempting to update the totals info in `entries`, *all* of the child tags will update (which I actually didn't realize). Even when doing, e.g.:
```
this.update({
    subtotalTime: subtotalTimeNew,
    totalTime: totalTimeNew
});
```
This is issue when, for example, a single `entry` tag is deleted. The first instance will work fine, but following instances will error our because RiotJS expects the deleted `entry` tag to be there because the contents of `entries.entries` has not been updated.

Also, if an `entry` tag is edited, the update to `entries` will overwrite the updated tag for the same reason (`entries.entries` is not updated).

Any thoughts on how to work with this? The fact that the above `update()` example refreshes all tags seems sort of troublesome overall for RiotJS, but perhaps we just need to rethink our tag strategy?

**Comment by overshard** [comment]
It seems we need to not unmount the object but use the method detailed in the guide under "Event handlers with looped items": http://riotjs.com/guide/

This will remove it from the collection

**Comment by overshard** [comment]
I've improved the remove on entries to update the parent entry list properly now.

**Comment by cdubz** [comment]
Nice! Determining the index in the patent array was where I got stuck. I didn't realize `indexOf` can take an object.

I won't be able to work on this tonight or tomorrow so feel free to continue with it. I'll pick it back up or find something new on Weds.

**Comment by overshard** [comment]
cdubz has got this working in the latest update
