### ISSUE TITLE
Buttons don't work in Chrome

### ISSUE THREAD

**Issue by msander** [overshard/timestrap#69]
You are using event.explicitOriginalTarget at multiple places. This is mozilla-only and does not work in other browsers. What are the advantages over event.target ?

**Comment by overshard** [comment]
I'm not sure, I think @cdubz implemented these when he setup buttons to toggle busy state.

@cdubz Is there are reason for the explicitOriginalTarget or can we swap these over to just target?

Thank you for bringing this up though @msander, we haven't started cross-browser testing much yet since we are still in early development but if you notice any other issues in Chrome let me know and I'll mark them as bug to be fixed so we have a list of them at least.

**Comment by cdubz** [comment]
Oops! I didn't realize that is Mozilla specific. I remember having some issue with`event.target` being the parent of the actual button or something. Anyway I will re-examine and implement a cross-browser solution.

**Comment by cdubz** [comment]
The issue was that buttons inside `<form>` elements pass the entire form for `event.target`. We have a mix of buttons both inside and outside of `<form>` elements, so the function has been modified to handle both cases, eliminating the reliance on `event.explicitOriginalTarget`. Thanks, @msander!

**Comment by msander** [comment]
@cdubz I guess, that this only applies to different events. onClick should always be the button itself, onSubmit should be the form.

**Comment by cdubz** [comment]
Ah, makes sense! I assume RiotJS triggers a submit if the button is inside a `<form>`, but only triggers click if it is not (which also makes sense). We could standardize how we implement buttons throughout, but for now the "busy" function handles both cases well enough.
