### ISSUE TITLE
Make most settings available via admin panel

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#76]
API keys for invoicing payment services, enable/disable parts of the app like invoicing and dashboard, brand customization, logo, name, etc.

**Comment by cdubz** [comment]
#118 gets the ball rolling by adding a "conf" app and enabling [Django's "sites" framework](https://docs.djangoproject.com/en/1.11/ref/contrib/sites/). The approach is similar to that of [Mezzanie](https://github.com/stephenmcd/mezzanine).

Some notes on the implementation:

- Django's core sites functionality is overridden to rely on the current domain instead of the static `SITE_ID` setting.
- By default, Timestrap will have only one site (with domain `time.strap` and name "Timestrap").
- The site name will be displayed in the UI where appropriate (this is currently the only "branding" bit).
- The super user can add additional sites (domain + name).
- Client & Task models can be associated with multiple sites (in theory).
- Entry & Invoice models are associated with one site only.

There are still a number of items to address:

- [ ] Decide on and implement permissions (who can add/edit sites?)
- [ ] Add ability for super users to manage site relationships on relevant models.
- [ ] Add ability for super users to see and manage *all* content in one place.
- [ ] Add tests.
- [ ] Come up with and implement other branding/configuration options.
